---
abstract: '32-bit block cipher based on Skipjack'
author:
  - 'Eric Hammond <eric-cpan@thinksome.com>'
build_requires:
  Test::More: 0.62
  Test::NoWarnings: 0.084
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Skip32
provides:
  Crypt::Skip32:
    file: lib/Crypt/Skip32.pm
    version: 0.17
recommends:
  Crypt::CBC: 2.22
  Crypt::Skip32::XS: 0
  Test::Distribution: 0
requires:
  perl: v5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
