---
name: Crypt-Skip32
version: 0.15
author:
  - 'Eric Hammond <eric-cpan@thinksome.com>'
abstract: 32-bit block cipher based on Skipjack
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0.62
  Test::NoWarnings: 0.084
requires:
  perl: v5.8.0
recommends:
  Crypt::CBC: 2.22
  Crypt::Skip32::XS: 0
  Test::Distribution: 0
configure_requires:
  Module::Build: 0.35
dynamic_config: 0
provides:
  Crypt::Skip32:
    file: lib/Crypt/Skip32.pm
    version: 0.15
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
